# These are supported funding model platforms

# GitHub Sponsors
github: s123104

# Open Collective
# open_collective: claude-night-pilot

# Patreon
# patreon: claude-night-pilot

# Ko-fi
# ko_fi: claude-night-pilot

# Custom funding links
custom: ['https://buymeacoffee.com/s123104', 'https://paypal.me/s123104']