// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 統一的 API 響應格式
 * 確保所有 API 端點返回一致的響應結構
 */
export type ApiResponse<T> = { 
/**
 * 操作是否成功
 */
success: boolean, 
/**
 * 響應資料（成功時包含）
 */
data?: T, 
/**
 * 錯誤或成功訊息
 */
message?: string, 
/**
 * 響應時間戳
 */
timestamp: string, 
/**
 * 請求 ID（用於追蹤和偵錯）
 */
request_id?: string, };
