// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionStatus } from "./ExecutionStatus";
import type { StreamChunk } from "./StreamChunk";
import type { UsageStats } from "./UsageStats";

/**
 * Claude CLI 執行響應
 */
export type ClaudeResponse = { 
/**
 * 響應 ID
 */
id: string, 
/**
 * 對應的請求 ID
 */
request_id: string, 
/**
 * 執行狀態
 */
status: ExecutionStatus, 
/**
 * 輸出內容
 */
output?: string, 
/**
 * 錯誤訊息
 */
error?: string, 
/**
 * 執行時間 (毫秒)
 */
execution_time_ms?: bigint, 
/**
 * 使用統計
 */
usage_stats?: UsageStats, 
/**
 * 流式數據片段 (stream-json 模式)
 */
stream_chunks: Array<StreamChunk>, 
/**
 * 響應時間
 */
created_at: string, 
/**
 * 完成時間
 */
completed_at: string | null, 
/**
 * 元數據
 */
metadata: { [key: string]: string }, };
