// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionOptions } from "./ExecutionOptions";
import type { RequestSource } from "./RequestSource";

/**
 * Claude CLI 執行請求
 */
export type ClaudeRequest = { 
/**
 * 請求 ID
 */
id: string, 
/**
 * 提示內容
 */
prompt: string, 
/**
 * 執行選項
 */
options: ExecutionOptions, 
/**
 * 請求時間
 */
created_at: string, 
/**
 * 請求來源 (CLI/GUI)
 */
source: RequestSource, 
/**
 * 會話 ID (用於續接)
 */
session_id?: string, 
/**
 * 元數據
 */
metadata: { [key: string]: string }, };
