// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 執行選項配置
 */
export type ExecutionOptions = { 
/**
 * 跳過權限確認
 */
skip_permissions: boolean, 
/**
 * 輸出格式 (json/text/stream-json)
 */
output_format: string, 
/**
 * 超時時間 (秒)
 */
timeout_seconds?: bigint, 
/**
 * 乾運行模式
 */
dry_run: boolean, 
/**
 * 工作目錄
 */
working_directory?: string, 
/**
 * 允許的操作類型
 */
allowed_operations: Array<string>, 
/**
 * 安全檢查
 */
safety_check: boolean, 
/**
 * 最大重試次數
 */
max_retries: number, 
/**
 * 使用 @ 符號文件引用
 */
enable_file_references: boolean, 
/**
 * 流式輸出處理
 */
stream_processing: boolean, };
