// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 執行狀態
 */
export type ExecutionStatus = "Running" | "Success" | "Failed" | "Cancelled" | "Timeout" | "Cooldown";
