// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分頁響應資料結構
 */
export type PaginatedResponse<T> = { 
/**
 * 當前頁面資料
 */
items: Array<T>, 
/**
 * 總記錄數
 */
total_count: bigint, 
/**
 * 當前頁碼（從 1 開始）
 */
page: number, 
/**
 * 每頁大小
 */
page_size: number, 
/**
 * 總頁數
 */
total_pages: number, 
/**
 * 是否有下一頁
 */
has_next: boolean, 
/**
 * 是否有上一頁
 */
has_prev: boolean, };
