// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 流式數據片段
 */
export type StreamChunk = { 
/**
 * 片段類型
 */
chunk_type: string, 
/**
 * 內容
 */
content: string, 
/**
 * 時間戳
 */
timestamp: string, 
/**
 * 序號
 */
sequence: bigint, 
/**
 * 是否最後一個片段
 */
is_final: boolean, };
