// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 使用統計資訊
 */
export type UsageStats = { 
/**
 * 輸入 token 數
 */
input_tokens: bigint, 
/**
 * 輸出 token 數
 */
output_tokens: bigint, 
/**
 * 總 token 數
 */
total_tokens: bigint, 
/**
 * 費用 (USD)
 */
cost_usd: number | null, 
/**
 * 模型名稱
 */
model: string | null, 
/**
 * API 調用次數
 */
api_calls: number, 
/**
 * 緩存命中
 */
cache_hits: number, };
