// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeRequest } from "../../src/types/ClaudeRequest";
import type { ClaudeResponse } from "../../src/types/ClaudeResponse";
import type { PerformanceMetrics } from "./PerformanceMetrics";
import type { RetryAttempt } from "./RetryAttempt";
import type { SecurityAudit } from "./SecurityAudit";

/**
 * 完整的執行結果，包含請求、響應和審計資訊
 */
export type ExecutionResult = { 
/**
 * 執行結果 ID
 */
id: string, 
/**
 * 原始請求
 */
request: ClaudeRequest, 
/**
 * 執行響應
 */
response: ClaudeResponse, 
/**
 * 安全審計資訊
 */
security_audit?: SecurityAudit, 
/**
 * 性能指標
 */
performance_metrics?: PerformanceMetrics, 
/**
 * 重試歷史
 */
retry_history: Array<RetryAttempt>, 
/**
 * 標籤和分類
 */
tags: Array<string>, 
/**
 * 創建時間
 */
created_at: string, 
/**
 * 最後更新時間
 */
updated_at: string, };
