// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionStatus } from "../../src/types/ExecutionStatus";
import type { PerformanceGrade } from "./PerformanceGrade";
import type { RiskLevel } from "./RiskLevel";
import type { UsageStats } from "../../src/types/UsageStats";

/**
 * 執行摘要 (用於列表顯示)
 */
export type ExecutionSummary = { id: string, status: ExecutionStatus, execution_time_ms?: bigint, usage_stats?: UsageStats, risk_level: RiskLevel, performance_grade?: PerformanceGrade, retry_count: number, created_at: string, };
