// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 檔案引用類型
 */
export type FileReferenceType = "File" | "Directory" | "Glob" | "GitRepo";
