// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileReferenceType } from "./FileReferenceType";

/**
 * 檔案引用
 */
export type FileReference = { 
/**
 * 引用名稱 (在提示中的佔位符)
 */
name: string, 
/**
 * 檔案路徑或 glob 模式
 */
path: string, 
/**
 * 引用類型
 */
ref_type: FileReferenceType, 
/**
 * 是否必須存在
 */
required: boolean, 
/**
 * 讀取限制 (字節)
 */
max_size_bytes?: bigint, 
/**
 * 檔案類型限制
 */
allowed_extensions: Array<string>, 
/**
 * 描述
 */
description?: string, };
