// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobExecutionOptions } from "./JobExecutionOptions";
import type { JobStatus } from "./JobStatus";
import type { JobType } from "./JobType";
import type { NotificationConfig } from "./NotificationConfig";
import type { RetryConfig } from "./RetryConfig";

/**
 * 排程工作任務
 */
export type Job = { 
/**
 * 工作 ID
 */
id: string, 
/**
 * 工作名稱
 */
name: string, 
/**
 * 關聯的提示 ID
 */
prompt_id: string, 
/**
 * Cron 表達式
 */
cron_expression: string, 
/**
 * 工作狀態
 */
status: JobStatus, 
/**
 * 工作類型
 */
job_type: JobType, 
/**
 * 優先級 (1-10, 10 最高)
 */
priority: number, 
/**
 * 執行選項
 */
execution_options: JobExecutionOptions, 
/**
 * 重試配置
 */
retry_config: RetryConfig, 
/**
 * 通知配置
 */
notification_config?: NotificationConfig, 
/**
 * 下次執行時間
 */
next_run_time?: string | null, 
/**
 * 上次執行時間
 */
last_run_time?: string | null, 
/**
 * 執行次數
 */
execution_count: bigint, 
/**
 * 失敗次數
 */
failure_count: bigint, 
/**
 * 標籤
 */
tags: Array<string>, 
/**
 * 元數據
 */
metadata: { [key: string]: string }, 
/**
 * 創建時間
 */
created_at: string, 
/**
 * 更新時間
 */
updated_at: string, 
/**
 * 創建者
 */
created_by?: string, };
