// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceLimits } from "./ResourceLimits";

/**
 * 工作執行選項
 */
export type JobExecutionOptions = { 
/**
 * 超時時間 (秒)
 */
timeout_seconds: bigint, 
/**
 * 並行執行限制
 */
max_parallel_executions: number, 
/**
 * 跳過如果前一個還在執行
 */
skip_if_running: boolean, 
/**
 * 工作目錄
 */
working_directory?: string, 
/**
 * 環境變數
 */
environment_variables: { [key: string]: string }, 
/**
 * 資源限制
 */
resource_limits?: ResourceLimits, };
