// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工作狀態
 */
export type JobStatus = "Active" | "Paused" | "Running" | "Completed" | "Cancelled" | "Failed" | "Cooldown";
