// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationChannel } from "./NotificationChannel";

/**
 * 通知配置
 */
export type NotificationConfig = { 
/**
 * 啟用通知
 */
enabled: boolean, 
/**
 * 成功時通知
 */
notify_on_success: boolean, 
/**
 * 失敗時通知
 */
notify_on_failure: boolean, 
/**
 * 開始時通知
 */
notify_on_start: boolean, 
/**
 * 通知方式
 */
notification_channels: Array<NotificationChannel>, 
/**
 * 自定義訊息模板
 */
custom_message_template?: string, };
