// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerformanceGrade } from "./PerformanceGrade";

/**
 * 性能指標
 */
export type PerformanceMetrics = { 
/**
 * 總執行時間 (毫秒)
 */
total_execution_time_ms: bigint, 
/**
 * Claude CLI 啟動時間 (毫秒)
 */
cli_startup_time_ms: bigint, 
/**
 * 網路延遲 (毫秒)
 */
network_latency_ms?: bigint, 
/**
 * 記憶體使用峰值 (MB)
 */
peak_memory_mb?: bigint, 
/**
 * CPU 使用率峰值 (%)
 */
peak_cpu_percent?: number, 
/**
 * 磁碟 I/O (MB)
 */
disk_io_mb?: bigint, 
/**
 * 性能等級
 */
performance_grade: PerformanceGrade, 
/**
 * 瓶頸分析
 */
bottlenecks: Array<string>, };
