// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 性能等級
 */
export type PerformanceGrade = "Excellent" | "Good" | "Average" | "Poor" | "Critical";
