// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileReference } from "./FileReference";
import type { PromptCategory } from "./PromptCategory";
import type { PromptVariable } from "./PromptVariable";

/**
 * 提示模板
 */
export type Prompt = { 
/**
 * 提示 ID
 */
id: string, 
/**
 * 提示名稱
 */
name: string, 
/**
 * 提示內容
 */
content: string, 
/**
 * 提示描述
 */
description?: string, 
/**
 * 提示類別
 */
category: PromptCategory, 
/**
 * 標籤
 */
tags: Array<string>, 
/**
 * 變數定義
 */
variables: Array<PromptVariable>, 
/**
 * 檔案引用 (@ 符號)
 */
file_references: Array<FileReference>, 
/**
 * 版本資訊
 */
version: string, 
/**
 * 是否啟用
 */
enabled: boolean, 
/**
 * 使用次數
 */
usage_count: bigint, 
/**
 * 平均執行時間 (毫秒)
 */
avg_execution_time_ms?: bigint, 
/**
 * 成功率 (0.0-1.0)
 */
success_rate?: number, 
/**
 * 最後使用時間
 */
last_used_at?: string | null, 
/**
 * 元數據
 */
metadata: { [key: string]: string }, 
/**
 * 創建時間
 */
created_at: string, 
/**
 * 更新時間
 */
updated_at: string, 
/**
 * 創建者
 */
created_by?: string, };
