// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptCategory } from "./PromptCategory";

/**
 * 提示範本
 */
export type PromptTemplate = { 
/**
 * 範本 ID
 */
id: string, 
/**
 * 範本名稱
 */
name: string, 
/**
 * 範本內容
 */
template: string, 
/**
 * 支援的變數
 */
supported_variables: Array<string>, 
/**
 * 範本描述
 */
description?: string, 
/**
 * 範本類別
 */
category: PromptCategory, 
/**
 * 是否為系統範本
 */
is_system_template: boolean, };
