// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 提示類別
 */
export type PromptCategory = "General" | "Development" | "Analysis" | "Documentation" | "Testing" | "Automation" | "Research" | "Creative" | { "Custom": string };
