// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationRule } from "./ValidationRule";
import type { VariableType } from "./VariableType";

/**
 * 提示變數定義
 */
export type PromptVariable = { 
/**
 * 變數名稱
 */
name: string, 
/**
 * 變數類型
 */
var_type: VariableType, 
/**
 * 變數描述
 */
description?: string, 
/**
 * 預設值
 */
default_value?: string, 
/**
 * 是否必填
 */
required: boolean, 
/**
 * 驗證規則
 */
validation?: ValidationRule, 
/**
 * 可選值列表
 */
options: Array<string>, };
