// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 資源限制
 */
export type ResourceLimits = { 
/**
 * 最大記憶體 (MB)
 */
max_memory_mb?: bigint, 
/**
 * 最大 CPU 使用率 (%)
 */
max_cpu_percent?: number, 
/**
 * 最大磁碟使用 (MB)
 */
max_disk_mb?: bigint, };
