// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 重試策略
 */
export type RetryStrategy = "Fixed" | "ExponentialBackoff" | "Linear" | { "Custom": Array<bigint> };
