// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetryStrategy } from "./RetryStrategy";

/**
 * 重試配置
 */
export type RetryConfig = { 
/**
 * 最大重試次數
 */
max_retries: number, 
/**
 * 重試間隔 (秒)
 */
retry_interval_seconds: bigint, 
/**
 * 重試策略
 */
retry_strategy: RetryStrategy, 
/**
 * 退避倍數 (指數退避使用)
 */
backoff_multiplier: number, 
/**
 * 最大退避時間 (秒)
 */
max_backoff_seconds: bigint, };
