// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 重試嘗試記錄
 */
export type RetryAttempt = { 
/**
 * 嘗試次數
 */
attempt_number: number, 
/**
 * 失敗原因
 */
failure_reason: string, 
/**
 * 重試時間
 */
retry_timestamp: string, 
/**
 * 等待時間 (毫秒)
 */
wait_time_ms: bigint, 
/**
 * 重試策略
 */
retry_strategy: string, };
