// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 安全風險項目
 */
export type SecurityRisk = { 
/**
 * 風險類型
 */
risk_type: string, 
/**
 * 風險描述
 */
description: string, 
/**
 * 嚴重性分數 (0.0-1.0)
 */
severity: number, 
/**
 * 建議措施
 */
mitigation?: string, };
