// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskLevel } from "./RiskLevel";
import type { SecurityRisk } from "./SecurityRisk";

/**
 * 安全審計資訊
 */
export type SecurityAudit = { 
/**
 * 風險等級
 */
risk_level: RiskLevel, 
/**
 * 風險分數 (0.0-1.0)
 */
risk_score: number, 
/**
 * 檢測到的風險項目
 */
detected_risks: Array<SecurityRisk>, 
/**
 * 提示內容雜湊值 (SHA256)
 */
prompt_hash: string, 
/**
 * 敏感資料檢測
 */
sensitive_data_detected: boolean, 
/**
 * 審計時間
 */
audit_timestamp: string, 
/**
 * 審計版本
 */
audit_version: string, };
