// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 驗證規則
 */
export type ValidationRule = { 
/**
 * 最小長度
 */
min_length?: number, 
/**
 * 最大長度
 */
max_length?: number, 
/**
 * 正則表達式
 */
pattern?: string, 
/**
 * 最小值 (數字類型)
 */
min_value?: number, 
/**
 * 最大值 (數字類型)
 */
max_value?: number, 
/**
 * 自定義驗證函數
 */
custom_validator?: string, };
