// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 變數類型
 */
export type VariableType = "Text" | "Number" | "Boolean" | "Date" | "Email" | "Url" | "File" | "Directory" | "Choice" | "MultiChoice";
