name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: swatinem/rust-cache@v2
      with:
        workspaces: src-tauri

    - name: Install frontend dependencies
      run: npm install

    - name: Install Tauri dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Rust format check
      run: cd src-tauri && cargo fmt --all -- --check

    - name: Rust clippy
      run: cd src-tauri && cargo clippy --all-targets --all-features -- -D warnings

    - name: Run Rust tests
      run: cd src-tauri && cargo test --verbose

    - name: Frontend lint check
      run: npm run lint:check

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Build Tauri app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --verbose

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: swatinem/rust-cache@v2
      with:
        workspaces: src-tauri

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      run: cd src-tauri && cargo audit

    - name: Run npm audit
      run: npm audit --audit-level moderate

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm install

    - name: Install Tauri dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xvfb

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Start dev server
      run: npm run dev:frontend &
      
    - name: Wait for server
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:8081; do sleep 1; done'

    - name: Run E2E tests
      run: xvfb-run -a npm test
      env:
        CI: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: |
          test-results/
          playwright-report/
        retention-days: 30